version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - DESTINY_API_KEY=${DESTINY_API_KEY}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DESTINY_API_KEY=${DESTINY_API_KEY}
    restart: unless-stopped 